---
title: Country Codes
---
flowchart LR
subgraph "🇺🇸 US codes"
fips{{"FIPS 10-4"}} -.->|-3 +4| gec{{"GEC"}} -.->|-13 +1| irs{{"IRS MeF"}}
genc{{"GENC"}}
end
subgraph "🌐 Int'l codes"
nuts{{"🇪🇺 NUTS"}}
nato{{"🧭 old NATO"}}
iso{{"🌐 ISO 3166"}}
end
fips -.->|±| nato
iso -.->|±| genc

click iso "https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Decoding_table" "new NATO, ccTLD domains, ISO 639 language codes, ISO 4217 currency codes"
