%%{init: {'theme': 'neutral', 'timeline': {'disableMulticolor': true}}}%%
timeline
title 🌐 International Country Codes Timeline
1974 : ISO 3166 1ed
1981 : ISO 3166 2ed
1988 : ISO 3166 3ed
1993 : ISO 3166 4ed
1997 : ISO 3166-1 (countries) 1ed
2004 : NATO switches to ISO-based country codes
2006 : ISO 3166-1 2ed
2013 : ISO 3166-1 3ed
2020 : ISO 3166-1 4ed
