timeline
title The Dawn of Podcasting
Pre-podcasting : This American Life <br> (NPR, 1995)
     : Future Tense <br> (APR, 1996)
     : Wait Wait… <br> Don't Tell Me <br> (NPR, 1998)
     : Radiolab <br> (WNYC , 2002)
2004 : Daily Source Code <br> (Aug 13, until Nov 2013)
     %% https://en.wikipedia.org/wiki/Daily_Source_Code
     : Future Tense <br> (Nov 19)
     %% https://web.archive.org/web/20041120045511/http://www.publicradio.org/columns/futuretense/podcast.xml
     : Brainwashed Radio the Podcast Edition <br> (Dec 14)
     %% https://web.archive.org/web/20041221072822/http://www.brainwashed.com/podcast/podcast_rss.xml
2005 : Comic Geek Speak <br> (ep 3 Mar 3)
     %% https://web.archive.org/web/20050907072155/http://www.bryandeemer.com/cgs/rss.xml
     : Keith and the Girl <br> (Mar 8)
     %% https://web.archive.org/web/20061004225226/https://katg.libsyn.com/rss
     : This Week in Tech <br> (TWiT, ep 3 May 2)
     %% https://web.archive.org/web/20050503122704/http://twit.tv/
     : The Skeptics' Guide to the Universe <br> (May 4)
     %% https://web.archive.org/web/20060515174645/http://www.theskepticsguide.org/rss.xml
     : Escape Pod <br> (May 12)
     %% https://web.archive.org/web/20060112134329/http://www.escapepod.org/2005/05/
     : Irish and Celtic Music Podcast <br> (Jul 28)
     %% https://web.archive.org/web/20051229191845/http://www.celticmusicpodcast.com/2005/07/1-susan-hamlin-three-quarter-ale-dust.shtml
     : Entitled Opinions <br> (Sep 13)
     %% https://entitled-opinions.com/2005/09/13/laura-wittman-on-michel-tourniers-friday/
     : The Cory Doctorow Podcast <br> (Sep 26)
     %% https://web.archive.org/web/20051026000413/http://craphound.com/podcast.php
2006 : Uhh Yeah Dude <br> (Feb 11)
     %% https://www.patreon.com/posts/104346580?collection=825782
     : Wait Wait… <br> Don't Tell Me <br> (Feb 12)
     %% https://web.archive.org/web/20060418125634/http://www.npr.org/rss/podcast.php?id=35
     : Never Not Funny <br> (Apr 7)
     %% https://nevernotdb.com/pardcast-episode-one
     : Radiolab <br> (Apr 14)
     %% https://web.archive.org/web/20060617225235/http://feeds.wnyc.org/radiolab
     : Hardcore History <br> (Jul 27)
     %% https://www.dancarlin.com/product/hardcore-history-1-alexander-versus-hitler/
     : Savage Lovecast <br> (Oct 26)
     %% https://savage.love/lovecast/2006/10/26/welcome-to-the-very-first-savage-love-podcast-in-this-episode-the-woes-of/
     : Jordan, Jesse, Go! <br> (Dec 4)
     %% https://maximumfun.org/episodes/jordan-jesse-go/episode-1/
2007 : This American Life <br> (Mar 29)
     %% https://web.archive.org/web/20070329025437/http://www.thisamericanlife.org/podcast.xml
     : Friday Night Comedy from BBC Radio 4 <br> (Oct 5)
     %% https://web.archive.org/web/20071011031942/http://www.bbc.co.uk/radio/podcasts/fricomedy/
     : The Bugle <br> (Oct 14, paused 2014 to 2016)
     %% https://en.wikipedia.org/wiki/The_Bugle
2008 : The Moth <br> (Mar 5)
     %% https://web.archive.org/web/20080407092525/http://feeds.themoth.org/themothpodcast
     : The Adam Carolla Show <br> (Jul 21)
     %% https://web.archive.org/web/20080723141057/http://www.971freefm.com/pages/1247.php
2009 : WTF with Marc Maron <br> (Sep 1, until 2025)
     %% https://en.wikipedia.org/wiki/WTF_with_Marc_Maron
     : The Joe Rogan Experience <br> (Dec 24)
     %% https://en.wikipedia.org/wiki/The_Joe_Rogan_Experience
2010 : Pod F Tompkast <br> (Jul 29, until 2013)
     %% https://pft.libsyn.com/
     : The Smartest Man in the World <br> (Oct 28)
     %% https://web.archive.org/web/20110317204330/http://feeds.feedburner.com/TheSmartest
2013 : The Weekly Planet <br> (Sep 30)
     %% https://shows.acast.com/theweeklyplanet/episodes/1-underrated-comic-book-movies
