%%{init: {'theme': 'dark', 'timeline': {'disableMulticolor': true}}}%%
timeline
title 🇺🇸 US Country Codes Timeline
1994 : DIA 65-18
1995 : FIPS 10-4
2003 : DAFIF 0413 ed 7 Amdt. No. 3
2008 : NIST withdraws FIPS 10-4, NGA maintains it as GEC
2012 : DoD ITSC retires FIPS 10-4
2013 : DoD CIO establishes GENC, US version of ISO 3166
2014 : NGA retires GEC : IRS publishes MeF from GEC
